kind: Namespace
apiVersion: v1
metadata:
  name: persistence
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  namespace: persistence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl
  namespace: persistence
  labels:
    app.kubernetes.io/name: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubectl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubectl
    spec:
      containers:
        - name: kubectl
          image: workshop/kubectl
          imagePullPolicy: Never
          volumeMounts:
          - name: data-dir
            mountPath: /data
      volumes:
        - name: data-dir
          persistentVolumeClaim:
            claimName: data
