---
apiVersion: v1
kind: Namespace
metadata:
  name: management-tools
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: code-server-sa
  namespace: management-tools
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  namespace: management-tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-egress-only
  namespace: management-tools
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  - to:
    - ipBlock:
        cidr: 10.42.0.0/15
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-admin
  namespace: management-tools
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: code-server-read-pods
  namespace: management-tools
subjects:
- kind: ServiceAccount
  name: code-server-sa
  namespace: management-tools
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: management-tools
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: code-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: management-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      serviceAccountName: code-server-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: code-server
        image: codercom/code-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: PASSWORD
          value: "admin"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: code-data
          mountPath: /home/coder
      volumes:
      - name: code-data
        persistentVolumeClaim:
          claimName: data
---
kind: Namespace
apiVersion: v1
metadata:
  name: desktops
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: desktops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: lscr.io/linuxserver/webtop:ubuntu-xfce
        ports:
        - containerPort: 3000
---
kind: Namespace
apiVersion: v1
metadata:
  name: cyberchef
  labels:
    app.kubernetes.io/name: cyberchef
    exposed: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
  namespace: cyberchef
  labels:
    app.kubernetes.io/name: cyberchef
    app.kubernetes.io/part-of: cyberchef
spec:
  replicas: 6
  selector:
    matchLabels:
      app.kubernetes.io/name: cyberchef
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cyberchef
    spec:
      containers:
        - name: cyberchef
          image: ghcr.io/gchq/cyberchef:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cyberchef
  namespace: cyberchef
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cyberchef
  ports:
    - port: 80
---
kind: Namespace
apiVersion: v1
metadata:
  name: blabla
  labels:
    app.kubernetes.io/name: blabla
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: blabla
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.28-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: blabla
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/part-of: blabla
spec:
  ports:
    - port: 80
  selector:
    app.kubernetes.io/name: nginx