FROM rust:alpine AS builder

COPY . /app

WORKDIR /app

RUN cargo build


# ---------------------------
FROM scratch

COPY --from=builder /app/target/debug/hello-api /hello-api

USER 65532

CMD "/hello-api"