apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: only-important
  namespace: important-namespace
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    # allow traffic from other namespaces to port 80, if the namespaces are important
    - namespaceSelector:
        matchLabels:
          my-domain.foo/importance: high
    ports:
    - protocol: TCP
      port: 80

  - from:
    # allow everything from inside our namespace
    - podSelector: {} 