# fundamentals/manifests/pod.yaml
kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:1.28-alpine
      ports:
        - containerPort: 80
    - name: debian
      image: debian:stable-slim
      command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
